<h1 style="text-align: center;">Telco Customer Churn Analysis & Prediction</h1>

## Objective
The objective of this project is to identify customers who are likely to churn, enabling the business to take proactive retention actions and reduce revenue loss.

# 1. Importing Libraries

In this step, we import all necessary libraries for data analysis and modeling.

In [4]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import roc_curve, auc

# 2. Data Loading

In this step, we load the dataset and inspect the first few rows
to understand the structure of the data.

In [5]:
df = pd.read_excel("telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

# 3. Basic Data Understanding
The dataset was explored to understand its structure, data types, and check for missing values before further processing.

In [6]:
df.shape

(7043, 33)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [8]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [9]:
df.isnull().sum().to_frame(name = "Null Count")

                   Null Count
CustomerID                  0
Count                       0
Country                     0
State                       0
City                        0
Zip Code                    0
Lat Long                    0
Latitude                    0
Longitude                   0
Gender                      0
Senior Citizen              0
Partner                     0
Dependents                  0
Tenure Months               0
Phone Service               0
Multiple Lines              0
Internet Service            0
Online Security             0
Online Backup               0
Device Protection           0
Tech Support                0
Streaming TV                0
Streaming Movies            0
Contract                    0
Paperless Billing           0
Payment Method              0
Monthly Charges             0
Total Charges               0
Churn Label                 0
Churn Value                 0
Churn Score                 0
CLTV                        0
Churn Reason             5174

In [10]:
df.duplicated().sum()

np.int64(0)

# 4. Data Cleaning & Preprocessing

Data cleaning steps were performed to ensure data quality, including:
- Handling missing values
- Removing duplicate records
- Standardizing categorical values

These steps ensure the dataset is consistent and ready for analysis.

# 4.1  Removing Irrelevant and Leakage Columns

The following columns were removed as part of preprocessing:

- **Identifier Columns**: 
  CustomerID was removed because it is a unique identifier and does not contribute to prediction.

- **Geographical Columns**: 
  Country, State, City, Zip Code, Latitude, Longitude were removed as they do not significantly impact churn behavior and may introduce noise.

- **Redundant Columns**: 
  Count column was removed as it has no meaningful information.

- **Data Leakage Columns**: 
  Churn Value, Churn Score, and CLTV were removed because they contain post-derived information that could lead to data leakage.

- **Post-outcome Column**: 
  Churn Reason was removed as it is only available after the customer has churned, making it unsuitable for prediction.

In [11]:
drop_cols = [
    'CustomerID', 'Count', 'Country', 'State', 'City',
    'Zip Code', 'Lat Long', 'Latitude', 'Longitude',
    'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason'
]

df = df.drop(columns=drop_cols)

df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes

# 4.2  Fixing Data Types

The 'Total Charges' column is currently in object format. We convert it to numeric and handle any invalid values.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   object
 1   Senior Citizen     7043 non-null   object
 2   Partner            7043 non-null   object
 3   Dependents         7043 non-null   object
 4   Tenure Months      7043 non-null   int64
 5   Phone Service      7043 non-null   object
 6   Multiple Lines     7043 non-null   object
 7   Internet Service   7043 non-null   object
 8   Online Security    7043 non-null   object
 9   Online Backup      7043 non-null   object
 10  Device Protection  7043 non-null   object
 11  Tech Support       7043 non-null   object
 12  Streaming TV       7043 non-null   object
 13  Streaming Movies   7043 non-null   object
 14  Contract           7043 non-null   object
 15  Paperless Billing  7043 non-null   object
 16  Payment Method     7043 non-null   object
 17  Monthly Charges    7043 non-null   float64
 18  Total Charges      7043 non-null   object
 19  Churn Label        7043 non-null   object
dtypes: float64(1), int64(1), object(18)
memory usage: 1.1+ MB

In [13]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

In [14]:
df.isnull().sum().to_frame(name = "Null Count")

                   Null Count
Gender                      0
Senior Citizen              0
Partner                     0
Dependents                  0
Tenure Months               0
Phone Service               0
Multiple Lines              0
Internet Service            0
Online Security             0
Online Backup               0
Device Protection           0
Tech Support                0
Streaming TV                0
Streaming Movies            0
Contract                    0
Paperless Billing           0
Payment Method              0
Monthly Charges             0
Total Charges              11
Churn Label                 0

In [15]:
df[df["Total Charges"].isnull()]

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label
2234,Female,No,Yes,No,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
2438,Male,No,No,No,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
2568,Female,No,Yes,No,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
2667,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
2856,Female,No,Yes,No,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
4331,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
4687,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
5104,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5719,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6772,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6840,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

# 4.3  Handling Missing Values in Total Charges

Missing values in 'Total Charges' were observed only for customers with zero tenure. 
Since these customers are newly joined and have not incurred any charges yet, 
the missing values were replaced with 0 to reflect the business logic accurately.

In [16]:
df.loc[df['Total Charges'].isnull(), 'Total Charges'] = 0

In [17]:
df.isnull().sum().to_frame(name = "Null Count")

                   Null Count
Gender                      0
Senior Citizen              0
Partner                     0
Dependents                  0
Tenure Months               0
Phone Service               0
Multiple Lines              0
Internet Service            0
Online Security             0
Online Backup               0
Device Protection           0
Tech Support                0
Streaming TV                0
Streaming Movies            0
Contract                    0
Paperless Billing           0
Payment Method              0
Monthly Charges             0
Total Charges               0
Churn Label                 0

# 4.4  Checking Duplicate Records

In this step, we check whether there are any duplicate rows in the dataset and remove them if present.

In [19]:
df.duplicated().sum()

np.int64(22)

# 4.5  Removing Duplicate Records

Duplicate rows were identified in the dataset. 
These were removed to ensure data quality and avoid bias in model training.

In [20]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [21]:
df.columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label'],
      dtype='object')

# 4.6 Standardizing Categorical Values

Certain columns contained values like 'No internet service' and 'No phone service', 
which were standardized to 'No' to reduce category complexity and ensure consistency 
for model training.

In [23]:
cols = [
    'Online Security','Online Backup','Device Protection',
    'Tech Support','Streaming TV','Streaming Movies'
]

for col in cols:
    df[col] = df[col].replace({'No internet service':'No'})

df['Multiple Lines'] = df['Multiple Lines'].replace({'No phone service':'No'})

In [24]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes

# 4.7  Standardizing Column Names

Column names were converted to lowercase and spaces were replaced with underscores 
to ensure consistency, improve readability, and make them easier to use in code.

In [26]:
df.columns = df.columns.str.lower().str.replace(' ', '_')